<a href="https://colab.research.google.com/github/qwerty141516/2026-BDA-repository/blob/main/code/04w1_ch04_%EB%8B%A4%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4_%EA%B2%B0%ED%95%A9%EA%B3%BC_%EB%B6%84%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열 결합

- numpy.vstack()
  - 배열을 수직으로 결합
  - 세로로 결합

- numpy.hstack()
  - 배열을 수평으로 결합
  - 가로로 결합

  > vertical : 수직의, 세로의
  
  > horizontal : 수평의, 가로의



# numpy.vstack( (a, b, ...) )

- 첫 인자인 tup는 튜플 자료형(또는 리스트)으로, tup는 합칠 여러 배열이며, 이 배열들은 0축을 제외한 모양이 동일

In [3]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# numpy.vstack( [x, y] )

- 인자인 배열이 1차원이면 길이가 같아야 수직으로 합칠 수 있음

- 1D -> 2D

In [6]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

# numpy.hstack()

> 수평으로 결합

- 1차원 배열
  - 무조건 수평으로 결합가능
  - 1D -> 1D

- 2차원 배열
  - 행이 같아야 함
  - 2D -> 2D

- 2차원 이상의 배열
  - 두 번째 축을 제외하고
    동일한 모양을 가져야 함

In [7]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [10]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

# np.column_stack( ( a, b ) )

> 2차원 배열 a,b를 수평으로 열(coulmns wise)로 결합

- 1차원 배열 a, b: 1D -> 2D
  - 배열 a와 b를 먼저 축 1로 확장한 이후, 열로 쌓아 만든 2차원 배열을 반환

- 2차원 배열 a, b: 2D -> 2D
  - 바로 np.hstack((a, b)) 동일

In [11]:
x = np.array([ 1, 2, 3 ])
y = np.array([ 10, 20, 30 ])
np.column_stack((x, y))

#np.column_stack((x[:, np.newaxis], y[:, np.newaxis])) 와 결과가 동일

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [13]:
x[:, np.newaxis]

# (3, ) 에서 (3, 1)로 변환

array([[1],
       [2],
       [3]])

In [14]:
np.hstack((x, y))

# 일반적으로 hstack()는 column_stack와 다름

array([ 1,  2,  3, 10, 20, 30])

In [15]:
np.column_stack == np.hstack

False

# numpy.row_stack()

> np.vstack()의 결과과 동일
  - 향후 없어질 함수, 대신 vstack()를 사용

In [16]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [18]:
np.row_stack((a, b))

/tmp/ipykernel_387/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

# numpy.concatenate( (a, b), axis = None | 0 | 1 )

> 기본적으로 축 0을 중심으로 합치는 기능을 수행, 결합하는 축을 수정 가능

- 1차원 배열 결합 1D -> 1D
  - 인자 axis는 쓸 필요 없음
    - axis = 1
      - 1차원에서 축은 0만 존재
        - 오류 발생

- 가로로 결합

In [19]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [20]:
np.concatenate((a,b,c), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [21]:
# 1차 배열인 경우 axis=0와 동일
np.concatenate((a,b,c), axis = None )

array([1, 2, 3, 4, 5, 6])

# numpy.concatenate() 2차원 배열 결합

- 기본은 axis = 0
  - 첫 축인 행으로 결합
    - 세로로 합하기
  - 열 수가 동일해야 함

- 2차원 배열에서
  - np.concatenate((x,y,z), axis = 0 )
  - np.concatenate((x,y,z))
  - np.vstack((x,y,z)) 동일

In [22]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [25]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [26]:
np.concatenate((x, y))

# vstack() , row_stack() 과 같은 기능 수행

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

# numpy.concatenate() 2차원 배열 결합, axis = 1

> 축 1로 합치므로 수평으로 결합, 즉 수평으로 합치려면 행 수가 같아야 함



In [27]:
np.concatenate((x, y), axis = 1)

# hstack , column_stack()과 같은 기능 수행

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [28]:
np.concatenate((x, y, z), axis = 1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [29]:
# 평면화 작업 후 연결
np.concatenate((x, y), axis=None)

# axis= 0 | 1 과 다름

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

# np.stack() 함수

> 주어진 둘 이상의 배열을 합쳐(쌓아) 차수가 1 증가한 하나의 배열로 생성

- 새 축을 따라 배열 시퀀스를 결합
  - 인자 axis
    - 결과 차원에서 새 축의 인덱스를 지정
    - axis = 0
      - 첫 번째 차원
    - axis = -1
      - 마지막 차원

- 차수가 하나 증가
  - 인자인 1차원 배열을 결합
    - 하나의 2차원 배열 생성
  - 인자인 2차원 배열을 결합
    - 하나의 3차원 배열 생성

- concatenate() 함수와 다름
  - np.stack()에 참여하는 배열
    - 모두 모양이 같아야 하며
  - np.stack()의 결과
    - axis에 지정한 축으로 차수가 하나 증가시켜 결합

# np.stack( (arr_1, arr_2), axis = 0 | 1 | 2 )

> 기본 값 axis = 0

In [30]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [31]:
b = np.array([4, 5 ,6])
b

array([4, 5, 6])

In [32]:
np.stack(( a, b ))

# np.row_stack()과 동일

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.stack(( a, b ) , axis = 1)

# np.column_stack()과 동일
# (3, )을 (3, 1)의 2차원으로 바꾸어 가로로 합치기

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
np.stack(( a, b ), axis= -1)

# axis = 1 은 -1 과 동일

array([[1, 4],
       [2, 5],
       [3, 6]])

# 3차원 배열 이해

> shape ( 4, 3, 2 )
  - 3행 2열의 2차원 배열이 4개 모임

  

# np.stack(( arr_1, arr_2), axis = 0 )

> 모양 (2, 3)의 2차원 행렬 x, y, z

- 3차원 생성에서 axis = 0
  - 늘어날 축이 0이며 축 0으로 결합

In [44]:
x = np.arange(6).reshape(2, 3)
x



array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
y = np.arange(10, 16).reshape(2, 3)
y



array([[10, 11, 12],
       [13, 14, 15]])

In [46]:
z = np.arange(20, 26).reshape(2, 3)
z


array([[20, 21, 22],
       [23, 24, 25]])

In [47]:
ax0 = np.stack((x, y, z), axis = 0)
ax0

# 3차원 배열이 결과
# 모양이 (2, 3)에서 (1, 2, 3)으로 변환

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

# np.stack((arr_1, arr_2), axis = 1)

> 모양 (2, 3)의 2차원 행렬 x, y, z

- 3차원 생성에서 axis = 1

In [49]:
x = np.arange(6).reshape(2, 3)
x

#(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
y = np.arange(10, 16).reshape(2, 3)
y

#(2, 3)

array([[10, 11, 12],
       [13, 14, 15]])

In [52]:
z = np.arange(20, 26).reshape(2, 3)
z

#(2, 3)

array([[20, 21, 22],
       [23, 24, 25]])

In [53]:
ax1 = np.stack((x, y, z), axis = 1)
ax1




array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [55]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
ax1.shape

# 3개를 합치므로 3이 됨

(2, 3, 3)

# np.stack((arr_1, arr_2), axis = 2)

> 모양 (2,3)의 2차원 행렬 x, y, z

- 3차원 생성에서 axis = 2

In [58]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [60]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [61]:
ax2 = np.stack((x, y, z), axis = 2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

# np.stack((arr_1, arr_2) , axis = 0 | 1 | 2)

- x, y, z 모양 : (2, 3)
- stack 결과 모양
  - 결합하는 배열 수
    - n = 3
  - axis = 0
    - ( n , 2 , 3 )
  - axis = 1
    - ( 2 , n , 3 )
  - axis = 2
    - (2 , 3 , n )

# column_stack()와 hstack()

> 1차원 입력의 결과는 다름

- 2차원
  - 결과가 동일
  

In [70]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
c = np.array([1, 3, 5])
c

array([1, 3, 5])

In [72]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [73]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

# row_stack()과 vstack()

> row_stack()과 vstack()은 완전히 같은 함수

- row_stack()는 없어질 함수
  - 함수 vstack()을 사용

- a : 2차, b: 1차 배열
  - vstack( (a, b) ) 가능
    - 열 수가 같으면 가능

In [74]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [76]:
np.row_stack((a, b))

/tmp/ipykernel_387/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [77]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# np.c_[]
> 함수는 아니고 대괄호 인덱스 []를 사용해 배열 객체 반환

- 대괄호 인덱싱 문법을 통해 열 방향으로 배열을 결합하는 도구

- 배열을 열 방향(2번째 축)으로(concatenation along the second axis, 즉 column-wise) 연결
  - 슬라이싱 문법을 지원하여, 인덱싱이나 슬라이싱과 함께 사용 가능

- 주요 특징
  - 배열 결합
    - 여러 배열을 수평(가로) 방향으로 쉽게 결합
  - 1차원 배열 확장
    - 1차원 배열을 자동으로 2차원으로 확장한 뒤 열로 결합

In [81]:
import numpy as np

# 두 개의 1D 배열을 열 방향으로 결합

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

# 이 코드는 두 1차원 배열 [1, 2, 3]과 [4, 5, 6]을
# 세로로 결합하여 다음과 같은 결과를 출력합니다

[[1 4]
 [2 5]
 [3 6]]


# np.c_[]와 np.column_stack()
> 1행의 2차원 배열

In [82]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [85]:
np.c_[x, y]

# 2차원일시 옆으로 그냥 붙임

array([[1, 2, 3, 4, 5, 6]])

In [86]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [87]:
np.c_[x, 10, 20, y]

# 스칼라 값도 삽입 가능

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [88]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

# np.r_[] 개요
> 수평으로 또는 수직으로도 합칠 수 있는 다양한 결합 방법을 제공

- 다양한 결합이 가능

- 1차원 벡터들을 나열
  - 그대로 1차원의 나열로 결합

- 배열이 n차원
  - 기본적으로 인자인 슬라이스 객체를 첫 번째 축(axis=0)을 따라 연결해 변환

In [89]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [90]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [92]:
np.row_stack((a, b))

#  1차원은 아래로 붙임

/tmp/ipykernel_387/2364025884.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

# np.r_['i', a, b]
> i: 결합(쌓는)하는 축(axis) 지정

- np.r_['0', a, a]
  - 배열 a 2개를 첫 축인 축 0으로 결합

In [93]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [95]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [96]:
np.r_['-1', a, a]

#np.r_['-1', a, a]: 배열 a 2개를 마지막 축인 축 1로 결합

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [97]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# np.split(ary) 개요
> 인자 ary를 여러 개의 부분 배열로 분리, 반환 값은 분리한 배열의 목록(list)

# np.vsplit(a) np.hsplit(a)
> 2차원 배열의 분리

- 함수 np.split(a, axis=0)
  - np.vsplit(a)와 동일

- 함수 np.split(a, axis = 1)
  - np.hsplit(a)와 동일

# np.split(ary, n)

>배열을 뷰(view)인 여러 개의 하위 배열로 분할



In [98]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [99]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

# np.split(ary, [i, j, k, ...])

- 정렬된 정수의 1차원 배열인 경우
- 항목은 배열이 축을 따라 분할되는 위치를 나타냄


In [100]:
import numpy as np

y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [101]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [102]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

# 다차원 배열 np.split(ary, n, axis = 1)

- np.hsplit(ary, n)

- np.split(a, 3, axis = 1)
  - 배열 a를 축 1 방향(수평으로 이동하며)으로
3개로 분리하면 12/3 = 4이므로
  - 4개의 열로 구성된 분할 배열 목록

In [104]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [105]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [106]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

# 다차원 배열 np.split(ary, n, axis=0)

- np.split(a, 3, axis=0)
  - 배열 a를 축 0 방향(수직으로 이동하며)으로
3개로 분리하면 6/3 = 2이므로
  - 2개의 행으로 구성된 분할 배열 목록

# 다차원 배열 np.split(ary, [i, j, k, …], axis= 0 | 1)

> [0, i) [i, j) [j, k) [k, …) 분리된 배열 리스트

In [107]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [108]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

# np.hsplit(ary, n)

In [111]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.hsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]])]

In [112]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

# np.hsplit(a, (3, 5, 8))

- 축 1 방향의 슬라이싱 인자 (3, 5, 8)
  - a[:, :3], a[:, 3:5], a[:, 5:8], a[:, 8:]의 슬라이싱
결과의 2차원 배열로 분할한 목록을 반환

In [113]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [114]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [115]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [116]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

# np.vsplit(a, n)

- 행 6개
  - 분리 수 3개
  - 2개의 행으로 구성된 배열로 분리

- 행 6개
  - 분리 수 4개
  - 나누어지지 않아 오류 발생


In [117]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [118]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [119]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

# np.vsplit(a, [i, j, k])

- 첨자가 (0, 4, 6)
  - 마지막 6으로 시작하는 배열은
  원소가 없는 배열
    - array([])

In [120]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [121]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [122]:
a[:1, :]

array([[0, 1, 2]])

In [123]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [124]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

# 3차원 배열의 vsplit(a, n)
> 수직으로 분할하는 np.vsplit()은 무조건 첫 번째 축인 axis=0로 n 등분 분할

- np.split(a, n, axis=0)과 동일
- 2차원 배열 (4, 4, 2)를 축 0으로 2개로 분할
  - (2, 4, 2)와 (2, 4, 2)로 분할

In [126]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [127]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [128]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

# 3차원 배열의 vsplit(a, [i, j, …])

> 축 0으로 슬라이싱 구간 [i, j, …]으로 분할

- np.vsplit(x, [1, 3])
  - x[:1, :, :]
  - x[1:3, :, :]
  - x[3:, :, :]

In [129]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [130]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

# 3차원 배열의 hsplit(a, n)
> 3차원 이상에서의 hsplit()은 두 번째 축인 axis=1로 n 등분 분할

- np.split(a, axis=1)와 동일
- 2차원 배열 (4, 4, 2)를 축 1로 2개 분할
  - (4, 2, 2)와 (4, 2, 2)로 분할

In [131]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [132]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

# 3차원 배열의 hsplit(a, [i, j, …])
> 축 axis=1에 따라 분리

- 원 배열의 모양 (4, 4, 2)
  - [1, 3]
    - 축 1에 따라
      다음 3 부분으로 분리
        - :1, 1:3, 3: 으로 분리

In [133]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [134]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

# 난수 기초

- 난수 생성기(제너레이터)
  - numpy.Random.default_rng
    - 난수를 만드는 생성기의 생성자
    - rng
      - 난수 생성기 RNG(Random Number Generator)

- 다음 코드로 실수 난수를 만드는 제너레이터를 하나 생성
  - 인자 12345는 비트제너레이터를 초기화 하는 시드 값
    - 시드 값이 같으면 호출 순서에 따라 난수가 발생하는 값이 동일
  

In [135]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x79B7A9937E60

# 난수 제너레이터의 함수 random()

- rg.random() : [0:1) 실수 난수


In [136]:
# [0, 1) 범위에 균일하게 분포된 하나의 무작위 부동소수점을 생성합니다.

r = rg.random()
r

0.22733602246716966

In [137]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [138]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

# 난수 제너레이터의 함수 integers()

- rg.intergers(low=0, high=10, size=3)
  - [low, high)에서 난수 3개
    - low, low + 1, low + 2, ... < high 시퀀스 정수 중에서 난수 3개
    

In [139]:
import numpy as np

rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [141]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

# 난수 생성자 함수 standard_normal()

> 정규 분포 난수 발생
  > 표준 정규분포: 68, 95, 99.7

- rg.standard_normal(10)
  - 정규 분포 난수 10개

In [142]:
import numpy as np

rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [143]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])